### PR TITLE
All changes completed.

### PR DESCRIPTION
**Pull request by rabocse**

### CODE REVIEW

**Review by konradbjk — CHANGES_REQUESTED** [review]
please remove go.mod files

**Comment by rabocse** [comment]
go.mod files should not create any issue and can help if the user is using a Go version where this is mandatory.

**Comment by rabocse** [comment]
Added section "Compile and Execute"
The section contains "go mod", "go build" and "go run" which are required to start to work with Go source code.

**Review by konradbjk — APPROVED** [review]
Okay, details are explained in the README

**Pull request merged**
